Spotify control component
Bragi3000/Bragi3000 pull request #29
Opened 2022-03-29 14:40 UTC by nikolim

Basic spotify control component to show the current track and play/pause button

2022-03-29 17:18 UTC, Atema reviewed
Looks nice and clean! Just one quick comment for now (will look at it more deeply later):

Instead of storing the images in the `public` folder, put them in the `Assets/images` folder, and then simply importing them into the file like follows:

```js
import playIcon from "Assets/images/play-icon.png";

<img src={playIcon} />
```

(You can take a look at the spinner in `WaitingView`, I did the same there.)

Then webpack will make sure everything is in the right place, optimise it for caching etc., and you can skip the hastle with `process.env.PUBLIC_URL`.

2022-03-29 17:56 UTC, nikolim commented
Thanks, I was actually not sure how to do it properly :)

2022-03-29 18:19 UTC, Atema requested changes
As said, looks pretty good overall. The main thing left is that the same data is currently stored in several states, which is confusing as all have to be kept in sync (which it seems is not always done at the moment)

2022-03-29 18:19 UTC, Atema commented on src/Components/SpotifyControl/SpotifyControl.js
> +      setIsPlaying(playbackData.body.is_playing);
Ánd there's also `playBackState`, which contains more of the same data.

2022-03-29 18:19 UTC, Atema commented on src/Components/SpotifyControl/SpotifyControl.js
> +      setIsPlaying(playbackData.body.is_playing);
An option may be to just keep `playbackState` (pls get rid of the capital B :zipper_mouth_face:) for state management within the presenter, and than give the image, name, artist, and playing state as separate props to the view:

```jsx
<SpotifyControlView
  name={playbackState.item.name}
  artist={...
/>
```

2022-03-29 18:19 UTC, Atema commented on src/Components/SpotifyControl/SpotifyControl.js
> +    if (token) {
The `if (token)` check is technically not necessary, as long as the spotifyControl is only used on token-restricted pages.

2022-03-29 18:19 UTC, Atema commented on src/Components/SpotifyControl/SpotifyControl.js
> +      setPlayBackState(getPlaybackState(token.access_token).then(handleData));
When doing the thing recommended below, this should be updated to something like:

```js
getPlaybackState(token.access_token)
  .then((newData) => {
    if (newData.statusCode === 200)
      setPlaybackState(newData); // Or newData.body, as the rest is not really necessary
  });

2022-03-29 18:20 UTC, Atema commented
And one more thing: if the place you got the icons also has SVG versions, they'd be preferrable: they are usually smaller and scale better to different sizes.

2022-03-30 19:15 UTC, Atema approved these changes
LGTM

2022-03-30 19:47 UTC, merged